services:
  web:
    image: ng2104/beelink:dev1.1
    container_name: beelink
    ports:
      - "3003:5000"
    environment:
      - SECRET_KEY=iiyew_ng2104
      - MONGO_URI=mongodb://iiyew:ng2104@mongo:27017/beelink?authSource=admin&authMechanism=SCRAM-SHA-1
    depends_on:
      - mongo
    networks:
      - beelink-net

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=iiyew
      - MONGO_INITDB_ROOT_PASSWORD=ng2104
      - MONGO_INITDB_DATABASE=beelink
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - beelink-net

volumes:
  mongo-data:

networks:
  beelink-net:
    driver: bridge
